### ISSUE TITLE
A way to output result files in another folder

### ISSUE THREAD

**Issue by DmitrySharabin** [LeaVerou/bafr#6]
Experimenting with https://github.com/LeaVerou/phd/issues/6, I thought how nice it would be if `Bafr` supported this feature. In that case, we could keep temporary `.tex` files in one place and remove them in one shot when we no longer need them.

It would be nice if we could specify such a folder either as a CLI parameter or a global setting (or both).
I'm unsure about the parameter's name. At first, I thought of something like `folder`, but with the `files` setting, it might be seen as a folder where the source files live. Another option might be `output`.

Suppose we go with `output`, then we can do the following:

```shell
bafr script.bafr.yaml --output=processed
```

And

```yaml
files: content/*.md
output: processed
replace:
- from: <br>
```

**Comment by LeaVerou** [comment]
Yup, I was thinking of that too. I think `path` would make more sense. The path would be resolved relative to the file’s existing path if relative, so we could do things like `path: ..`.

**Comment by LeaVerou** [comment]
This has now been implemented.
